import {
  WalletDisconnectButton,
  WalletMultiButton,
} from "@solana/wallet-adapter-react-ui";
import { useConnection, useWallet } from "@solana/wallet-adapter-react";
import * as bs58 from 'bs58';
import type { NextPage } from "next";
import React, { useState, useEffect } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Message, Transaction } from "@solana/web3.js";

const Home: NextPage = () => {
  const [response, setResponse] = useState<string | undefined>();
  const { connection } = useConnection();
  const { publicKey, wallet, signTransaction } = useWallet();

  const handleSubmit = (async (event: any) => {
    // Stop the form from submitting and refreshing the page.
    event.preventDefault()
    const encodedTransaction = event.target.encoded_transaction.value;
    const transactionBuffer = bs58.decode(encodedTransaction);
    const transaction = Transaction.populate(Message.from(transactionBuffer));
    console.log(transaction);
    // const signedTx = await signTransaction?.(transaction);
    // if (signedTx) {
    //   console.log(signedTx.signatures[1].publicKey.toBase58());
      
      const completedTransaction = await wallet?.adapter.sendTransaction(transaction, connection)
      setResponse(completedTransaction)
      return completedTransaction;
    // }
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.walletButtons}>
        <WalletMultiButton />
        <WalletDisconnectButton />
      </div>
      <div>
        <h3>
          Wallet Address: <code>{publicKey?.toBase58()}</code>
        </h3>
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label>Encoded Transaction</label>
            <textarea
              name="encoded_transaction"
              className="form-control"
              id="encoded_transaction"
              placeholder="Enter transaction"
            />
          </div>
          <button type="submit" className="btn btn-warning">
            Submit
          </button>
        </form>
        <div>
          { response }
        </div>
      </div>
      <main className={styles.main}></main>
    </div>
  );
};

export default Home;
